name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
#    - name: Update packages
#      run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
    
#    - name: Compile
#      run: cmake -DCMAKE_BUILD_TYPE=Release -DWITH_BOOST_TEST=ON
    
    - name: Compile
      run: cmake -S . -B build && cmake --build build --config Release

#    - name: Build
#      run: cmake --build .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
