name: Release-Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare to compile
      run: cmake -S homework_1 -B build -DVER_REVISION=${{github.run_number}} -DIS_WINDOWS=ON

    - name: Compile
      run: cmake --build build --config Release
