name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Compile
      run: cmake -DCMAKE_BUILD_TYPE=Release
      run: cmake --build .
